title: <p align="center"> Jarvis R </p>
logo: /assets/img/Jarvis.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jarvis-ravichandran-20892626/">LinkedIn</a> |
  <a href="https://github.com/Jarvisravi">GitHub</a>
  
  <br>   
  I am currently doing Machine Learning & Artificial Intelligence at Upgrad & IIITB
  Worked with Photon as Lead iOS Mobile App Developer
  <br>
  </p>


theme: jekyll-theme-minimal


